### ISSUE TITLE
CaffeineSpecSpringAutoConfiguration cacheManager @ConditionalOnMissingBean by type

### ISSUE THREAD

**Issue by mserdur** [stepio/coffee-boots#11]
Hi
CaffeineSpecSpringAutoConfiguration.cacheManager is annotated with @ConditionalOnMissingBean and by default it makes a type check to determine if there is already such a bean. I think in this case we should be checking the bean by name: _cacheManager_ since we are trying to understand if there is a default cache manager defined.
Fortunately there is a way to configure that annotation by bean name using the _name_ attribute.
So, could you please update that annotation as:
@ConditionalOnMissingBean(name="cacheManager")

Background about how I bumped into this:
I wanted to configure a LoadingCache via properties file but it is not supported by this project. So I extended it, and using my own custom CacheManager as the default cache manager. So they are clashing because CaffeineSpecSpringAutoConfiguration is alse trying to register a bean with the same name: _cacheManager_
You can see some details of how I am doing it here: https://github.com/ben-manes/caffeine/issues/311 in case you also want to use a LoadingCache.

**Comment by stepio** [comment]
Hello @mserdur ,

Thank you very much for finding my project helpful and sorry for ignoring this issue for such a long time.

I checked your solution and also checked how `Spring Boot` handles this. They use next approach which I'd prefer to "copy":
```java
@ConditionalOnMissingBean(
    value = {CacheManager.class},
    name = {"cacheResolver"}
)
```

Looks like such update should help you as well. Makes sense?
