### ISSUE TITLE
Upgrade to Spring Boot 3

### ISSUE THREAD

**Issue by Telamon-m** [stepio/coffee-boots#164]
Hi,
Can you please provide a version of coffee boots which is based on Spring Boot 3? This would be very helpful.
Thanks.

**Comment by Telamon-m** [comment]
Hi @stepio ,
I opened to PRs:

1. https://github.com/stepio/coffee-boots/pull/171 For upgrading to latest version 2 of spring boot
2. https://github.com/stepio/coffee-boots/pull/172 For upgrading to 3 of spring boot

All tests are running successfully.
Can you please merge and release the new versions?

**Comment by stepio** [comment]
Thanks for the contributions, @Telamon-m !

Published: https://central.sonatype.com/artifact/io.github.stepio.coffee-boots/coffee-boots/4.0.0
