### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by CH-EricLundberg** [stepio/coffee-boots#38]
Trying to switch to coffee-boots, previously I could get metrics on the caches via prometheus and micrometer, when I switch to configuring the caches with coffee-boots they drop off the metrics endpoints. Any thoughts on how to get them back? I am using the same caffeinespec for all the caches, just changing the configuration from spring.cache... to coffeeboots.cache...

**Comment by stepio** [comment]
Thanks for pointing this out, I’ll check

**Comment by CH-EricLundberg** [comment]
👍 I don't have a sample project, but am using spring-boot with:

```
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
```

and looking at /actuator/prometheus endpoint

**Comment by stepio** [comment]
Would you please also tell which versions of `spring-boots`, `micrometer` and `coffee-boots` do you use?

**Comment by stepio** [comment]
Seems that it's the way Spring Boot works now:
https://stackoverflow.com/questions/49697063/after-upgrade-to-spring-boot-2-how-to-expose-cache-metrics-to-prometheus
In short: metrics do not work out of the box for dynamically created caches.

But I'll check a bit more.

**Comment by stepio** [comment]
Implemented the change here:
https://github.com/stepio/coffee-boots/pull/39

Pushed snapshot to Maven Central:
https://oss.sonatype.org/content/repositories/snapshots/io/github/stepio/coffee-boots/coffee-boots/2.1.0-SNAPSHOT/coffee-boots-2.1.0-20200112.212325-1.jar.asc

Works for me on a sample project:
https://github.com/stepio/coffee-boots-example

Please let me know what you think.

**Comment by CH-EricLundberg** [comment]
👍 LGTM!

**Comment by stepio** [comment]
Merged and created new release:
https://github.com/stepio/coffee-boots/releases/tag/2.1.0
